#!/bin/bash

# This script runs the analytics endpoint tests with the correct tokens

node scripts/test_analytics_endpoints.js "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MTMyNGIyYi0zOWQ2LTQ4NmQtODc1Yi0wNGQwZjEwM2M0OWEiLCJlbWFpbCI6Imhvb3RzZDFAbW9udGNsYWlyLmVkdSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NjEyODU4MSwiZXhwIjoxNzQ2MjE0OTgxfQ.wuECC4eSvPYZ_bC1D6uTunPOCO0AgtBseFUCLjHKF3M" "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MTMyNGIyYi0zOWQ2LTQ4NmQtODc1Yi0wNGQwZjEwM2M0OWEiLCJ0b2tlblR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNzQ2MTI4NTgxLCJleHAiOjE3NDY3MzMzODF9.0OE4CbVjw3TjnVdZ4QBANYE0XrqU1UcWYCmJpcgqG7Y"
